# Esto es un comentario

# Para ejecutar este archivo:
#   >docker-compose up

# Definimos la versi칩n (En este caso '3' es OBLIGATORIO)
version: '3'

# Definimos los servicios que vamos a utilizar
services:
  # Servicio de NoSQL
  mongo:
    image: mongo
    container_name: mongo_products
    ports:
      - "27017:27017"

  # Servicio de Productos
  products:
    build:
      context: ./ProductsService
      dockerfile: Dockerfile
    container_name: productos_service
    ports:
      - "5071:5071"
    environment:
      # Entorno de desarrollo para ASP.NET Core
      - ASPNETCORE_ENVIRONMENT=Development
      # Cadena de conexi칩n a MongoDB usando el nombre del servicio interno de Docker
      - Mongo__ConnectionString=mongodb://mongo:27017
      # URL de escucha para el servicio de productos
      - ASPNETCORE_URLS=http://+:5071
      # API Keys v치lidas para autenticaci칩n
      - API_KEYS=key_test_local
    depends_on:
      - mongo

  # Servicio de Inventario
  inventory:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    container_name: inventario_service
    ports:
      - "5117:5117"
    environment:
      # Entorno de desarrollo para ASP.NET Core
      - ASPNETCORE_ENVIRONMENT=Development
      # URL de escucha para el servicio de inventario
      - ASPNETCORE_URLS=http://+:5117
      # URL interna para que el servicio de inventario consuma el de productos
      - PRODUCTS_API_BASE=http://products:5071
    depends_on:
      - products